version: '3'

services:
  wg:
    image: tivix/docker-nginx:v11
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./index.html:/var/www/html/index.html  
    logging:
      driver: json-file
      options:
        max-size: 50m
    environment:
      - MAINTENANCE=true
