name: Deploy Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy Nginx to Host 1
      run: |
        # Copy docker-compose.yml and index.html to host 1
        scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.HOST1_IP }}:/tmp/docker-compose.yml
        scp -o StrictHostKeyChecking=no ./index.html ${{ secrets.SSH_USER }}@${{ secrets.HOST1_IP }}:/tmp/index.html

        # Run docker-compose on host 1
        ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST1_IP }} << EOF
          cd /tmp
          sudo docker-compose down
          sudo docker-compose up -d
        EOF

    - name: Deploy Nginx to Host 2
      if: success()
      run: |
        # Copy docker-compose.yml and index.html to host 2
        scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.HOST2_IP }}:/tmp/docker-compose.yml
        scp -o StrictHostKeyChecking=no ./index.html ${{ secrets.SSH_USER }}@${{ secrets.HOST2_IP }}:/tmp/index.html

        # Run docker-compose on host 2
        ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST2_IP }} << EOF
          cd /tmp
          sudo docker-compose down
          sudo docker-compose up -d
        EOF
