name: Deploy Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy Nginx to Host 1
      run: |
        scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.HOST1_IP }}:/tmp/docker-compose.yml
        scp -o StrictHostKeyChecking=no index.html ${{ secrets.SSH_USER }}@${{ secrets.HOST1_IP }}:/tmp/index.html
    
        ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST1_IP }} << 'EOF'
          cd /tmp
          sudo docker-compose down
          sudo docker-compose up -d 
          sleep 10
          
          sed -i "s/{{HOSTNAME}}/\$(hostname)/g" /tmp/index.html
          
          sudo docker cp /tmp/index.html proxy:/var/www/html/index.html
        EOF

    - name: Deploy Nginx to Host 2
      if: success()
      run: |
        scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.HOST2_IP }}:/tmp/docker-compose.yml

        # Run docker-compose on host 2
        ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST2_IP }} << EOF
          cd /tmp
          sudo docker-compose down &&
          sudo docker-compose up -d &&
          sudo docker exec proxy /bin/sh -c "echo '<p>Host: '$(hostname)'</p>' >> /var/www/html/index.html" || true
        EOF
