name: Deploy Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      COMPOSE_FILE: docker-compose.yml

    strategy:
      matrix:
        host: [host1, host2] 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 

    - name: Deploy Nginx to Host
      run: |
        if [ "${{ matrix.host }}" == "host1" ]; then
          export SSH_HOST=${{ secrets.HOST1_IP }}
        elif [ "${{ matrix.host }}" == "host2" ]; then
          export SSH_HOST=${{ secrets.HOST2_IP }}
        fi

        # Copy docker-compose.yml to host
        scp $COMPOSE_FILE ${{ secrets.SSH_USER }}@$SSH_HOST:/tmp/docker-compose.yml
        scp ./index.html ${SSH_USER}@${{ matrix.host }}:/var/www/html/

        # Run docker-compose on host
        ssh ${{ secrets.SSH_USER }}@$SSH_HOST << EOF
          cd /tmp
          docker-compose down
          docker-compose up -d
        EOF
